// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbGQF1wpW93Epv4_D-zdmX2XwUq3L2YWk',
    appId: '1:347107196998:web:d606f86262b3ac3ae78a47',
    messagingSenderId: '347107196998',
    projectId: 'biomecanica-d2746',
    authDomain: 'biomecanica-d2746.firebaseapp.com',
    databaseURL: 'https://biomecanica-d2746-default-rtdb.firebaseio.com',
    storageBucket: 'biomecanica-d2746.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiXJKqtw-p5HkY_W0Wqoa6-KyGCY88aZg',
    appId: '1:347107196998:android:110d3dda1f84c22ce78a47',
    messagingSenderId: '347107196998',
    projectId: 'biomecanica-d2746',
    databaseURL: 'https://biomecanica-d2746-default-rtdb.firebaseio.com',
    storageBucket: 'biomecanica-d2746.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAz4LNkUli8shGoPtWWrhMRYT02qV3XxUM',
    appId: '1:347107196998:ios:24c78ccdc1e677b6e78a47',
    messagingSenderId: '347107196998',
    projectId: 'biomecanica-d2746',
    databaseURL: 'https://biomecanica-d2746-default-rtdb.firebaseio.com',
    storageBucket: 'biomecanica-d2746.appspot.com',
    iosClientId: '347107196998-tk2kl8qogqj3ptn1ip0ealtg065hvka7.apps.googleusercontent.com',
    iosBundleId: 'com.example.appBiomecanica',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAz4LNkUli8shGoPtWWrhMRYT02qV3XxUM',
    appId: '1:347107196998:ios:a378693990621ad0e78a47',
    messagingSenderId: '347107196998',
    projectId: 'biomecanica-d2746',
    databaseURL: 'https://biomecanica-d2746-default-rtdb.firebaseio.com',
    storageBucket: 'biomecanica-d2746.appspot.com',
    iosClientId: '347107196998-237860pqne3eom07o32p839r0kcl0psc.apps.googleusercontent.com',
    iosBundleId: 'com.example.appBiomecanica.RunnerTests',
  );
}
